# Generated by Django 4.1.5 on 2023-01-18 04:04

from django.db import migrations, models
import django.db.models.deletion
import soilcarbon.helpers.model_helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SourceFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                (
                    "csv_file",
                    models.FileField(
                        upload_to="field_sources/%Y/%m/%d/",
                        validators=[soilcarbon.helpers.model_helpers.validate_is_csv],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Farm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("farm_name", models.CharField(max_length=200, unique=True)),
                ("location_boundary", models.CharField(max_length=500)),
                ("soil_organic_carbon", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farms",
                        to="soilcarbon.sourcefile",
                    ),
                ),
            ],
            options={
                "ordering": ("soil_organic_carbon",),
            },
        ),
    ]
