# Generated by Django 4.1.5 on 2023-01-18 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("soilcarbon", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="farm",
            old_name="location_boundary",
            new_name="geographical_boundaries",
        ),
    ]
