# Generated by Django 4.1.5 on 2023-01-20 18:46

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("soilcarbon", "0004_alter_farm_geographical_boundaries"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="geographical_boundaries",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                geography=True, srid=4326
            ),
        ),
    ]
