# Generated by Django 4.1.5 on 2023-02-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("soilcarbon", "0005_alter_farm_geographical_boundaries"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourcefile",
            name="file_slug",
            field=models.SlugField(default="test_file1", max_length=500, unique=True),
            preserve_default=False,
        ),
    ]
