version: "3.7"

services:
  web:
    build: .
    command: python manage.py runserver --settings=grow_everything.config.dev 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    networks:
      - proxynet

  db:
    image: postgres:12.0-alpine
    networks:
      - proxynet
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=soilcarbon
      - POSTGRES_PASSWORD=soilcarbon
      - POSTGRES_DB=soilcarbon

networks:
  proxynet:
    name: soil_carbon_project

volumes:
  postgres_data:
