services:

  database:
    container_name: tambua_shamba_database
    image: kartoza/postgis:12.0
    networks:
      - proxynet
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=soilcarbon
      - POSTGRES_PASSWORD=soilcarbon
      - POSTGRES_DB=soilcarbon
    restart: "on-failure"

  backend-server:
    container_name: tambua_shamba_server
    build:
      context: ./tambuashamba_server
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/tambuashamba_server
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    networks:
      - proxynet
    restart: "on-failure"
    depends_on:
      - database
  
  frontend-server:
    container_name: tambua_shamba_client
    build: 
      context: ./tambuashamba_client
    volumes:
      - .:/frontend-server
      - /frontend-server/node_modules
    ports:
      - 4200:4200
    env_file:
      - ./.env.dev
    networks:
      - proxynet
    restart: "on-failure"
    depends_on:
      - backend-server

networks:
  proxynet:
    name: groweverything_network

volumes:
  postgres_data:
