# Generated by Django 4.1.5 on 2023-01-20 16:46

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("soilcarbon", "0003_alter_farm_geographical_boundaries_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="geographical_boundaries",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
